Fix squid container proxy for RHEL 7
rhinstaller/kickstart-tests pull request #407
Opened 2020-11-16 14:55 UTC by martinpitt

With these patches I can successfully run kickstart-tests with the local http proxy on our RHEL 7 e2e machines:
```
# containers/squid.sh start
# containers/runner/launch --skip-testtypes rhel-only,knownfailure --jobs 27 all
```

I started that now, I'll update this description once it finished and I have a total runtime. Last time I tried that was with 25 parallel jobs and no proxy, which took about 2:50 hours. (The machine does not have enough RAM/storage to run 32 tests in parallel).

2020-11-16 18:50 UTC, jkonecny12 requested changes
Looks good to me. However, do we want to support both ``iptables`` and ``nft``? Wouldn't it be easier to just use iptables for everything?

Also do we need to support RHEL-7? Anaconda won't be released on RHEL-7 anymore so there is no reason to keep testing it.

2020-11-16 19:02 UTC, martinpitt commented
@jkonecny12 : iptables is being deprecated, and Eric Garver says that nft is the new way forward. On developer machines we should use nft, like firewalld itself.

About RHEL 7, this isn't about testing a RHEL-7 install, but running the runner container *on* a RHEL 7 system. Unfortunately our e2e machines are stuck on RHEL 7 and can't currently be reinstalled with RHEL 8. We'll discuss that on Wednesday, but for now I think these are our best bet.

2020-11-18 14:44 UTC, martinpitt commented
@jkonecny12 : I took out the iptables patch. I can put it back in if/when we need to run on e2e, or perhaps Satellite gets fixed by then :crossed_fingers:

2020-11-18 14:58 UTC, jkonecny12 commented
> @jkonecny12 : I took out the iptables patch. I can put it back in if/when we need to run on e2e, or perhaps Satellite gets fixed by then crossed_fingers

Sounds great to me. Thanks!

2020-11-18 14:59 UTC, jkonecny12 approved these changes
LGTM!

2020-11-18 15:21 UTC, merged