Add new driverdisk test which will test inst.dd kernel args
rhinstaller/kickstart-tests pull request #623
Opened 2021-11-09 13:23 UTC by jkonecny12

The driverdisk test is using kickstart command but it would be great to have both variants tested.

This will not work until https://github.com/rhinstaller/kickstart-tests/pull/621 is merged.

2021-11-09 13:30 UTC, VladimirSlavik requested changes
Can you use the standard includes please? I believe a lot of what you have is actually normalized. If not, please disregard this (dismiss?).

2021-11-09 13:46 UTC, jkonecny12 commented
Good point. I just copied the old test which seems to have this missing.

2021-11-09 14:40 UTC, jkonecny12 commented
**UPDATED:**
* Use fragments in these tests.

2021-11-09 14:40 UTC, VladimirSlavik approved these changes
Looks good to me. Thank you!

2021-11-10 10:07 UTC, rvykydal approved these changes
Looks good to me.

2021-11-10 12:04 UTC, M4rtinK approved these changes
Looks good to me as well.

2021-11-10 16:48 UTC, merged